// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

struct Pixel
{
    float2 Position;
    float3 Color;
};

RWStructuredBuffer<Pixel> PixelBuffer;
int PixelBufferSize = 0;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xy] = float4(id.x/((float)1024),0,0,0);
}
